name: publish

on:
    push:
        branches:
            - master

jobs:
    npm-publish:
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: read
        steps:
            - uses: actions/checkout@v3
              with:
                  persist-credentials: false
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: 'yarn'
            - name: Install
              run: |
                  yarn install --immutable
            - run: yarn build
            - name: publish
              run: npx semantic-release
              env:
                  GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
                  HUSKY: 0
